### ISSUE TITLE
Suggestion: Add commit amend

### ISSUE THREAD

**Issue by adrianaden** [summitech/gitexplorer#22]
Nice tool, summitech !!

i suggest to add _commit --amend_ in under **'commit'** option
commit --amend helps you to modify last commit that you already commit

**Comment by omentes** [comment]
https://github.com/summitech/gitexplorer/blob/master/src/data/secondary-options.js#L71

choose to "modify"

**Comment by adrianaden** [comment]
cool!! 👍 

i didn't see that already add in **modify** option
