### ISSUE TITLE
Suggestion: Create a branch from another branch

### ISSUE THREAD

**Issue by yasin3061** [summitech/gitexplorer#27]
It will be good to have a command to create a branch from another branch (apart from the currently checked out branch).

`git checkout -b myFeature dev`

**Comment by moizKachwala** [comment]
@FatimahSanni  Not able to push branch for pull request. error code 403

**Comment by omentes** [comment]
@moizKachwala 
1. Fork
2. clone you fork
2. git checkout -b myFeature
3. magic
4. git add <your magic>
5. git commit -m 'my magic'
6. git push 
7. create PR from your-fork/myFeature to origin/master
