### ISSUE TITLE
Request: Add a Git Stash command

### ISSUE THREAD

**Issue by dbilovd** [summitech/gitexplorer#37]
`git stash` is missing from the list of commands. Any reason why?

**Comment by aashutoshrathi** [comment]
Yes, please.
This is the first thing that I searched on the app.

**Comment by FatimahSanni** [comment]
This is part of the commands to be added this week.

**Comment by FatimahSanni** [comment]
Command has been added @dbilovd and @aashutoshrathi Thanks a lot for creating this issue 👍🏽
