### ISSUE TITLE
GitExplorer Domain

### ISSUE THREAD

**Issue by Jacolack** [summitech/gitexplorer#46]
Sorry if I'm misunderstanding, but is this the same repo that used to be https://gitexplorer.com ?
If so, it no longer points to the gitexplorer site.
Also, http://gitexplorer.com appears it is being parked.

**Comment by remiilekun** [comment]
@Jacolack https://gitexplorer.netlify.com/ appears to be going through

**Comment by FatimahSanni** [comment]
It's back up. Thanks @Jacolack and @remiilekun
