### ISSUE TITLE
prop-types package is not present in package.json

### ISSUE THREAD

**Issue by jaworek** [summitech/gitexplorer#60]
I noticed that `prop-types` is used in the project is missing from `package.json`.

Was it overlooked? I can make a PR to fix it.

**Comment by FatimahSanni** [comment]
That should be an oversight. Yes you can create a PR. Thank you!

**Comment by jaworek** [comment]
Would it be ok if I also updated other dependencies?
I think `firebase` is not used in the project, so I could remove it.
I can add `prettier` if you don't mind.
I'll also make separate with refactor and improvements.

**Comment by FatimahSanni** [comment]
Yeah, sure, you can do all these. Thanks a lot for the observations. Looking forward to seeing your PR

**Comment by KoltonG** [comment]
That is a great catch @jaworek! I saw that as well and wondered if there was something I was missing 😛. Do you need any help with creating the PR?

**Comment by ade-fatimah** [comment]
Thanks so much guys fro your PRs. It's very much appreciated. They've been merged.
