### ISSUE TITLE
Git Reset A File

### ISSUE THREAD

**Issue by KoltonG** [summitech/gitexplorer#63]
I was trying to find a way to reset a local file to a version on another branch but could not find anything like this in the **reset/revert** section. 

I found this link https://stackoverflow.com/a/37972822 which helped me solve my problem.

I'm wondering what you think about this and if it's possible to get this added to the project? I could also create a PR if this is alright!

**Comment by FatimahSanni** [comment]
Please create a PR. We'd appreciate that

**Comment by KoltonG** [comment]
@FatimahSanni I just created a PR to add this command 🥳
