### ISSUE TITLE
Forcing animation of text could be simplified.

### ISSUE THREAD

**Issue by jaworek** [summitech/gitexplorer#73]
Currently, to force animation of text to be repeated on option change application uses state in multiple places to do it.
It is possible to simplify and improve it by using keys on components that need to be recreated when selected value changes.
I'm happy to submit a PR, but from what I see this repo is not being updated for quite a while.
Let me know if this repo still accepts changes.

**Comment by ade-fatimah** [comment]
The repo still accepts changes. Sincere apologies for the delays in merging but we accept changes and we promise it's going to be much faster now.

**Comment by jaworek** [comment]
Great! I'll submit a PR later.
