### ISSUE TITLE
Adding PUSH in first option

### ISSUE THREAD

**Issue by kitarp29** [summitech/gitexplorer#80]
<h1>Adding PUSH in first option</h1>

Sir/Mam, I want to add a <b>PUSH </b>option in the first options list and add more commands related to it like (-f ,-u).
I found the "git push origin branchname" in the secondary-options.js 
<br>
BUT manually on the site I could'nt navigate to it.
If you guys want I will work on these features and generate a PULL REQUEST.
<br>
<img src="https://user-images.githubusercontent.com/56778773/91271533-f84b8c00-e797-11ea-91b5-e96fb0b34fe3.png" height="400" width="800">

**Comment by arthurdenner** [comment]
Hi @kitarp29! 👋 

You just found a bug. The `push` command has secondary options but it's missing on the primary options.

~~Feel free to fix this and add more commands related to it.~~

**Comment by arthurdenner** [comment]
@kitarp29, I just noticed that #79 addresses this bug.

Maybe you should wait for it before doing other changes.

**Comment by kitarp29** [comment]
Ok Sir, if I get some similar issue I let you know
